# This is the code: evaluates my saved model that I have trained and it get accuracy 99.55%

## *Download file "saved_model_acc995.h5" that is my saved model and run the code below.

In [1]:
#Download file "saved_model_acc995.h5" that is my saved model and run the code below.

# set up

# import tensorflow.compat.v1 as tf
# tf.disable_v2_behavior()

import tensorflow as tf
import numpy as np
# import matplotlib.pyplot as plt

from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.initializers import Initializer as KerasInitializer
from tensorflow.keras.datasets import mnist
from tensorflow.keras.callbacks import Callback
from tensorflow.keras import layers
from tensorflow.keras import initializers
from tensorflow.keras.layers import Conv2D, Lambda, MaxPooling2D
from tensorflow.keras.layers import BatchNormalization
from IPython.display import Image
from tensorflow.keras.preprocessing.image import ImageDataGenerator


In [2]:
# prepare dataset

# MNIST dataset parameters

input_shape = 28 # input shape: 28 X 28 = 784
num_classes = 10 # total classes (0-9 digits)

# import and load MNIST dataset, split between and test datasets

(x_train, y_train), (x_test, y_test) = mnist.load_data()

# normalize image pixcel values from [0, 255] to [0, 1]

x_train, x_test = x_train / 255., x_test / 255.

# convert class vectors into one-hot encoded format

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

# inspect an random sample

index = 128

print(y_train[index])
print(y_train[index].shape)
print(y_test[index])
print(y_test[index].shape)

x_train = x_train.reshape(-1,28,28,1)
x_test = x_test.reshape(-1,28,28,1)

# check the shape of MNIST images


print('MNIST dataset shapes:')
print('x_train: ' + str(x_train.shape))
print('y_train: ' + str(y_train.shape))
print('x_test: ' + str(x_test.shape))
print('y_test: ' + str(y_test.shape))

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
(10,)
MNIST dataset shapes:
x_train: (60000, 28, 28, 1)
y_train: (60000, 10)
x_test: (10000, 28, 28, 1)
y_test: (10000, 10)


In [3]:
PATH = "/work/saved_model_acc995.h5"
model = tf.keras.models.load_model(PATH)

In [4]:
# evaluate the saved model

score = model.evaluate(x_test, y_test, verbose = 0)
print("test loss:", score[0])
print("test accuracy:", score[1])

test loss: 0.016430335119366646
test accuracy: 0.9955000281333923


In [5]:
# make predictions: it is the prediction of each test sample

predictions = model.predict(x_test)
predictions = np.argmax(predictions, axis = 1)
print(predictions)

[7 2 1 ... 4 5 6]


# Below; this is the code that I created&gt;trained&gt; and saved to the model above 

## You can un-comments and try to run it

In [6]:
# import tensorflow as tf
# import numpy as np

# from tensorflow.keras.layers import Dense, Flatten
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.utils import to_categorical
# from tensorflow.keras.initializers import Initializer as KerasInitializer
# from tensorflow.keras.datasets import mnist
# from tensorflow.keras.callbacks import Callback
# from tensorflow.keras import layers
# from tensorflow.keras import initializers
# from tensorflow.keras.layers import Conv2D, Lambda, MaxPooling2D
# from tensorflow.keras.layers import BatchNormalization
# from IPython.display import Image
# from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [7]:
# input_shape = 28 # input shape: 28 X 28 = 784
# num_classes = 10 # total classes (0-9 digits)


# (x_train, y_train), (x_test, y_test) = mnist.load_data()


# x_train, x_test = x_train / 255., x_test / 255.

# y_train = to_categorical(y_train)
# y_test = to_categorical(y_test)

# index = 128

# print(y_train[index])
# print(y_train[index].shape)
# print(y_test[index])
# print(y_test[index].shape)

# x_train = x_train.reshape(-1,28,28,1)
# x_test = x_test.reshape(-1,28,28,1)

# print('MNIST dataset shapes:')
# print('x_train: ' + str(x_train.shape))
# print('y_train: ' + str(y_train.shape))
# print('x_test: ' + str(x_test.shape))
# print('y_test: ' + str(y_test.shape))

In [8]:
# buffer_size = 100000
# learning_rate = 0.1
# training_epochs = 50
# batch_size = 64
# patience = 10

In [9]:
# callback = tf.keras.callbacks.EarlyStopping(monitor = 'val_loss', patience = patience, verbose = 0)

In [10]:
# optimizer = tf.keras.optimizers.SGD(learning_rate = learning_rate) # optimizer

In [11]:
# model=Sequential()
    
# model.add(Conv2D(filters=64, kernel_size = (3,3), activation="relu", input_shape=(28,28,1)))
# model.add(Conv2D(filters=64, kernel_size = (3,3), activation="relu"))

# model.add(MaxPooling2D(pool_size=(2,2)))
# model.add(BatchNormalization())
# model.add(Conv2D(filters=128, kernel_size = (3,3), activation="relu"))
# model.add(Conv2D(filters=128, kernel_size = (3,3), activation="relu"))

# model.add(MaxPooling2D(pool_size=(2,2)))
# model.add(BatchNormalization())    
# model.add(Conv2D(filters=256, kernel_size = (3,3), activation="relu"))
    
# model.add(MaxPooling2D(pool_size=(2,2)))
    
# model.add(Flatten())
# model.add(BatchNormalization())
# model.add(Dense(512,activation="relu"))
    
# model.add(Dense(10,activation="softmax"))

# model.compile(loss="categorical_crossentropy", optimizer=optimizer, metrics=["accuracy"])  
    
# model.summary()

In [12]:
# datagen = ImageDataGenerator( # Data augmentation to prevent overfitting
#         featurewise_center=False,  # set input mean to 0 over the dataset
#         samplewise_center=False,  # set each sample mean to 0
#         featurewise_std_normalization=False,  # divide inputs by std of the dataset
#         samplewise_std_normalization=False,  # divide each input by its std
#         zca_whitening=False,  # apply ZCA whitening
#         rotation_range=10,  # randomly rotate images 
#         zoom_range = 0.1, # Randomly zoom image 
#         width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
#         height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
#         horizontal_flip=False,  # randomly flip images
#         vertical_flip=False)  # randomly flip images


# train_gen = datagen.flow(x_train, y_train, batch_size=64)
# test_gen = datagen.flow(x_test, y_test, batch_size=64)

In [13]:
# history = model.fit_generator(train_gen, 
#                               epochs = 50, 
#                               steps_per_epoch = x_train.shape[0] // batch_size,
#                               validation_data = test_gen,
#                               validation_steps = x_test.shape[0] // batch_size) # Fit the model

In [14]:
# score = model.evaluate(x_test, y_test, verbose = 0)
# print("test loss:", score[0])
# print("test accuracy:", score[1])

In [15]:
# predictions = model.predict(x_test)
# predictions = np.argmax(predictions, axis = 1)
# print(predictions)

In [16]:
# model.save('saved_model.h5')

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=4a5eb7c8-dcf2-4b88-b8eb-d1931de0d517' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>